workflows:
  telegram-ui-only:
    name: Telegram UI‑Only Simulator
    max_build_duration: 120
    environment:
      vars:
        # put your direct .zip download link here
        APP_URL: https://github.com/Gringo2/Telegram-iOS/releases/download/ui-only-build-31970/Telegram.app.zip
      xcode: latest

    scripts:
      - name: Download Telegram UI‑Only build
        script: |
          curl -L "$APP_URL" -o Telegram.app.zip
          unzip Telegram.app.zip

      - name: Boot iOS Simulator
        script: |
          xcrun simctl shutdown all || true
          xcrun simctl boot "iPhone 15"
          open -a Simulator
          until xcrun simctl list | grep -q "Booted"; do sleep 5; done

      - name: Install and launch
        script: |
          xcrun simctl install booted Telegram.app
          xcrun simctl launch booted org.telegram.Telegram
